name: ososs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  shimmer: ^3.0.0
  fluttertoast: ^8.2.2
  http: ^0.13.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  infinite_scroll_pagination: ^4.0.0-dev.1
  rxdart: ^0.27.3
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
